version: '1.0'

services: 
  currency-exchange: 
    image:  reddybvpr/springmicroservices-currency-exchange-service:0.0.1-SNAPSHOT
    ports: 
      - "8000:8000"
    networks: 
      - currency-network
    depends_on: 
      - naming-server
      - rabbitmq
    environment: 
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit


  currency-conversion: 
    image:  reddybvpr/springmicroservices-currency-conversion-service:0.0.1-SNAPSHOT
    ports: 
      - "8100:8100"
    networks: 
      - currency-network
    depends_on: 
      - naming-server
      - rabbitmq
    environment: 
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      
  api-gateway: 
    image:  reddybvpr/springmicroservices-api-gateway:0.0.1-SNAPSHOT
    ports: 
      - "8765:8765"
    networks: 
      - currency-network
    depends_on: 
      - naming-server
      - rabbitmq
    environment: 
      eureka.client.service-url.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.base-url: http://zipkin-server:9411
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      
  zipkin-server: 
    image:  openzipkin/zipkin:latest
    mem_limit: 300m
    ports: 
      - "9411:9411"
    networks: 
      - currency-network
    depends_on: 
      - rabbitmq
    environment: 
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      
  rabbitmq: 
    image:  rabbitmq:3.9.25-management-alpine
    mem_limit: 300m
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks: 
      - currency-network
      
  naming-server: 
    image:  reddybvpr/springmicroservices-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8761:8761"
    networks: 
      - currency-network
      
      
      
networks: 
  currency-network: 